/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import controle.Cliente;
import controle.Corretor;
import servico.Agenda;
import dao.AgendaDAO;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class FrameAgenda extends javax.swing.JFrame {
    
    private Corretor corretor;
    private Cliente cliente;
    
    /** Creates new form Agenda */
    public FrameAgenda() {
        initComponents();
    }
    public FrameAgenda(Corretor corretor) {
        this.corretor = corretor;
        initComponents();
        customInitComponents();
        setTitle("Agendamento");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Centraliza a janela
        setLayout(null);
    }
   
    private void customInitComponents() {
        // Aqui você pode adicionar código para configurar os componentes
        // com base no objeto corretor, por exemplo:
        if (corretor != null) {
            System.out.println("ID: "+ corretor.getId());
            System.out.println("Dados do corretor: "+ corretor.getEmail());
            //System.out.println("PIN: "+ corretor.getPin());
            System.out.println("Nº do CRECI: "+corretor.getCreci());
            System.out.println("Nome: "+corretor.getNome());
            System.out.println("Sobrenome: "+ corretor.getSobrenome());
        } else {
            JOptionPane.showMessageDialog(null, "O corretor tem que estar logado.");
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeClienteAgendar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataAtendimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoraAtendimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoAtendimento = new javax.swing.JComboBox<>();
        cmbCategoriaImovelAgendar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAgendarAtendimento = new javax.swing.JButton();
        btnAlterarAgendamento = new javax.swing.JButton();
        txtCodigoAgendamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDesmarcarAgendamento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdCorretor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Agenda Atlas");

        jLabel2.setText("Nome do Cliente");

        jLabel3.setText("data atendimento");

        txtDataAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAtendimentoActionPerformed(evt);
            }
        });

        jLabel4.setText("hora atendimento");

        txtHoraAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraAtendimentoActionPerformed(evt);
            }
        });

        jLabel5.setText("tipo de atendimento");

        cmbTipoAtendimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simular Financiamento", "Entregar Documentos", "Assinar Contrato", "Visita ao Imóvel", "Entrega das Chaves" }));

        cmbCategoriaImovelAgendar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Terreno", "Imóvel na planta" }));

        jLabel6.setText("Tipo de Imóvel");

        btnAgendarAtendimento.setText("Agendar");
        btnAgendarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarAtendimentoActionPerformed(evt);
            }
        });

        btnAlterarAgendamento.setText("Alterar");
        btnAlterarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAgendamentoActionPerformed(evt);
            }
        });

        jLabel8.setText("código do agendamento");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*** Informar código do agendamento para atualizar ou excluir");

        btnDesmarcarAgendamento.setText("Desmarcar");
        btnDesmarcarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesmarcarAgendamentoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("** corretor por favor  informar matricula");

        jLabel10.setText("Matrícula no Atlas");

        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("* Para agendar, preencha todos os campos acima.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(62, 62, 62))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtIdCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtCodigoAgendamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgendarAtendimento, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(btnDesmarcarAgendamento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterarAgendamento))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCategoriaImovelAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeClienteAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoraAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeClienteAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoraAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoriaImovelAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(btnAgendarAtendimento)
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarAgendamento)
                    .addComponent(btnDesmarcarAgendamento))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAtendimentoActionPerformed

    private void txtHoraAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraAtendimentoActionPerformed

    private void btnAgendarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarAtendimentoActionPerformed
        try {
            Cliente cliente = new Cliente();
            Agenda agenda = new Agenda();
            agenda.setNome_cliente(txtNomeClienteAgendar.getText());
            agenda.setCreci(corretor.getCreci());
            agenda.setData_atendimento(txtDataAtendimento.getText());
            agenda.setHora_atendimento(txtHoraAtendimento.getText());
            agenda.setTipo_atendimento((String) cmbTipoAtendimento.getSelectedItem());
            agenda.setImovel_categoria((String) cmbCategoriaImovelAgendar.getSelectedItem());
            agenda.setStatus(1);
            AgendaDAO agendaDAO = new AgendaDAO();
            if (agendaDAO.agendamento(agenda, corretor.getId())) {
                JOptionPane.showMessageDialog(null, "agendamento efetuado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Ops! houve um problema com o seu agendamento.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnAgendarAtendimentoActionPerformed

    private void btnAlterarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAgendamentoActionPerformed
        try {
            Cliente cliente = new Cliente();
            Agenda agenda = new Agenda();
            agenda.setCodigo(Integer.parseInt(txtCodigoAgendamento.getText()));
            int id_corretor=Integer.parseInt(txtIdCorretor.getText());
            agenda.setNome_cliente(txtNomeClienteAgendar.getText());
            agenda.setCreci(corretor.getCreci());
            agenda.setData_atendimento(txtDataAtendimento.getText());
            agenda.setHora_atendimento(txtHoraAtendimento.getText());
            agenda.setTipo_atendimento((String) cmbTipoAtendimento.getSelectedItem());
            agenda.setImovel_categoria((String) cmbCategoriaImovelAgendar.getSelectedItem());
            agenda.setStatus(1);
            if (id_corretor ==  corretor.getId()) {
                AgendaDAO agendaDAO = new AgendaDAO();
                agendaDAO.mudarAgendamento(agenda, corretor.getId());
                JOptionPane.showMessageDialog(null, "Mudanca no agendamento efetuada com sucesso");
            }else {
                JOptionPane.showMessageDialog(null, "Ops! ocorreu um erro ao mudar o agendamento.");
            }
           
        } catch (SQLException ex) {
            ex.printStackTrace();
        }catch (Exception e) {
        }
    }//GEN-LAST:event_btnAlterarAgendamentoActionPerformed

    private void btnDesmarcarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesmarcarAgendamentoActionPerformed
        try {
            int id_corretor=Integer.parseInt(txtIdCorretor.getText());
            Cliente cliente = new Cliente();
            Agenda agenda = new Agenda();
            agenda.setCodigo(Integer.parseInt(txtCodigoAgendamento.getText()));
            if (id_corretor ==  corretor.getId()) {
                AgendaDAO agendaDAO = new AgendaDAO();
                agendaDAO.desmarcarAgendamento(agenda, corretor.getId());
                JOptionPane.showMessageDialog(null, "Agendamento desmarcado com sucesso");
            }else {
                JOptionPane.showMessageDialog(null, "Ops! ocorreu um erro ao mudar o agendamento.");
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }catch (Exception e) {
        }
    }//GEN-LAST:event_btnDesmarcarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarAtendimento;
    private javax.swing.JButton btnAlterarAgendamento;
    private javax.swing.JButton btnDesmarcarAgendamento;
    private javax.swing.JComboBox<String> cmbCategoriaImovelAgendar;
    private javax.swing.JComboBox<String> cmbTipoAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCodigoAgendamento;
    private javax.swing.JTextField txtDataAtendimento;
    private javax.swing.JTextField txtHoraAtendimento;
    private javax.swing.JTextField txtIdCorretor;
    private javax.swing.JTextField txtNomeClienteAgendar;
    // End of variables declaration//GEN-END:variables

}
