/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import dao.ImovelDAO;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import servico.Imovel;
import servico.ManipulaImagem;

/**
 *
 * @author trabalho
 */
public class TelaCorretor extends javax.swing.JFrame {
    BufferedImage imagem; //tipo variavel armazena imagem em bytes 
    /**
     * Creates new form TelaCorretor
     */
    public TelaCorretor() {
        initComponents();
        setTitle("Principal");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Centraliza a janela
        setLayout(null);
    }

     private JPanel criarPainelImovel(Imovel imovel) {
        JPanel painelImovel = new JPanel();
        painelImovel.setLayout(new BoxLayout(painelImovel, BoxLayout.Y_AXIS));

        JLabel lblDescricao = new JLabel("Descrição: " + imovel.getDescricao());
        JLabel lblLocalidade = new JLabel("Localidade: " + imovel.getLocalidade());
        JLabel lblPreco = new JLabel("Preço: " + imovel.getPreco());

        JLabel lblImagem = new JLabel();
        ManipulaImagem.exibirImagemLabel(imovel.getImagem(), lblImagem);

        painelImovel.add(lblImagem);
        painelImovel.add(lblDescricao);
        painelImovel.add(lblLocalidade);
        painelImovel.add(lblPreco);

        return painelImovel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtLocalidadeImovel = new javax.swing.JTextField();
        cmbTipoImovel = new javax.swing.JComboBox<>();
        btnPesquisarImovel = new javax.swing.JButton();
        lblDescricao = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblDescricao1 = new javax.swing.JLabel();
        lblLocal1 = new javax.swing.JLabel();
        lblPreco1 = new javax.swing.JLabel();
        txtDescricaoImovel = new javax.swing.JTextField();
        btnBuscarDadosImovel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSignUp = new javax.swing.JMenu();
        mnCorretor = new javax.swing.JMenu();
        mnCorretorNovo = new javax.swing.JMenuItem();
        mnCorretorLogin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnVerTodosAnuncios = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Atlas");

        txtLocalidadeImovel.setText("localidade");
        txtLocalidadeImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalidadeImovelActionPerformed(evt);
            }
        });

        cmbTipoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Terreno", "Imóvel na planta" }));

        btnPesquisarImovel.setText("Pesquisar");
        btnPesquisarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarImovelActionPerformed(evt);
            }
        });

        lblDescricao1.setText("Descrição");

        lblLocal1.setText("Localidade:");

        lblPreco1.setText("Preço:");

        txtDescricaoImovel.setText("descrição");
        txtDescricaoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoImovelActionPerformed(evt);
            }
        });

        btnBuscarDadosImovel.setText("Buscar");
        btnBuscarDadosImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDadosImovelActionPerformed(evt);
            }
        });

        mnSignUp.setText("Criar Conta");

        mnCorretor.setText("Corretor");

        mnCorretorNovo.setText("novo");
        mnCorretorNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCorretorNovoActionPerformed(evt);
            }
        });
        mnCorretor.add(mnCorretorNovo);

        mnCorretorLogin.setText("login");
        mnCorretorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCorretorLoginActionPerformed(evt);
            }
        });
        mnCorretor.add(mnCorretorLogin);

        mnSignUp.add(mnCorretor);

        jMenuBar1.add(mnSignUp);

        jMenu2.setText("Imoveis");

        mnVerTodosAnuncios.setText("ver anúncios");
        mnVerTodosAnuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVerTodosAnunciosActionPerformed(evt);
            }
        });
        jMenu2.add(mnVerTodosAnuncios);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPreco1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao1)
                            .addComponent(lblLocal1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoImovel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLocalidadeImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisarImovel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnBuscarDadosImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocalidadeImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarDadosImovel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtDescricaoImovel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLocal1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreco1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarImovelActionPerformed
        try {
            ImovelDAO imovelDAO = new ImovelDAO();
            ArrayList<Imovel> imoveis = imovelDAO.listaImovel(txtLocalidadeImovel.getText(), cmbTipoImovel.getSelectedItem().toString());
            JPanel painelResultados = new JPanel();
            painelResultados.setLayout(new BoxLayout(painelResultados, BoxLayout.Y_AXIS));
            
            for (Imovel imovel : imoveis) {
                JPanel painelImovel = criarPainelImovel(imovel);
                painelResultados.add(painelImovel);
            }
            
            JScrollPane scrollPane = new JScrollPane(painelResultados);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            JFrame frameResultados = new JFrame("Resultados da Pesquisa");
            frameResultados.setSize(800, 600);
            frameResultados.add(scrollPane);
            frameResultados.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar imóveis: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarImovelActionPerformed

    private void mnCorretorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCorretorLoginActionPerformed
        FrameLogin login = new FrameLogin();
        login.setVisible(true);
    }//GEN-LAST:event_mnCorretorLoginActionPerformed

    private void mnCorretorNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCorretorNovoActionPerformed
        FrameNovoCorretor frameRegistro = new FrameNovoCorretor();
        frameRegistro.setVisible(true);
    }//GEN-LAST:event_mnCorretorNovoActionPerformed

    private void txtLocalidadeImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalidadeImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalidadeImovelActionPerformed

    private void btnBuscarDadosImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDadosImovelActionPerformed
        Imovel imovel = new Imovel();  //fazer paginaçao
        ImovelDAO imovelDAO;
        try {
            imovelDAO = new ImovelDAO();  //busca preço do imóvel no banco e exibe no jframe
            Imovel resultados = imovelDAO.pesquisarImovel(txtDescricaoImovel.getText());
            lblDescricao.setText(resultados.getDescricao());
            lblLocal.setText(resultados.getLocalidade());
            lblPreco.setText(Float.toString(resultados.getPreco()));
            ManipulaImagem.exibirImagemLabel(resultados.getImagem(), lblImagem);
            //lblImagem.setIcon(new ImageIcon());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Nada a ser visualizado aqui. " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarDadosImovelActionPerformed

    private void txtDescricaoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoImovelActionPerformed

    private void mnVerTodosAnunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVerTodosAnunciosActionPerformed
        try {
            ImovelDAO imovelDAO = new ImovelDAO();
            ArrayList<Imovel> imoveis = imovelDAO.listaImovel();
            JPanel painelResultados = new JPanel();
            painelResultados.setLayout(new BoxLayout(painelResultados, BoxLayout.Y_AXIS));
            
            for (Imovel imovel : imoveis) {
                JPanel painelImovel = criarPainelImovel(imovel);
                painelResultados.add(painelImovel);
            }
            
            JScrollPane scrollPane = new JScrollPane(painelResultados);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            JFrame frameResultados = new JFrame("Resultados da Pesquisa");
            frameResultados.setSize(800, 600);
            frameResultados.add(scrollPane);
            frameResultados.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar imóveis: " + ex.getMessage());
        }
    }//GEN-LAST:event_mnVerTodosAnunciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCorretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDadosImovel;
    private javax.swing.JButton btnPesquisarImovel;
    private javax.swing.JComboBox<String> cmbTipoImovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblLocal1;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JMenu mnCorretor;
    private javax.swing.JMenuItem mnCorretorLogin;
    private javax.swing.JMenuItem mnCorretorNovo;
    private javax.swing.JMenu mnSignUp;
    private javax.swing.JMenuItem mnVerTodosAnuncios;
    private javax.swing.JTextField txtDescricaoImovel;
    private javax.swing.JTextField txtLocalidadeImovel;
    // End of variables declaration//GEN-END:variables
}
